version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: techplatform_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - techplatform_net
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: techplatform_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://altynay_yertay:Altusha006$@tech-platform.bqirtmr.mongodb.net/techplatform?appName=tech-platform
      - JWT_SECRET=mysecretkey123
      - PORT=3000
      - NODE_ENV=production
    networks:
      - techplatform_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: techplatform_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - techplatform_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.0
    container_name: techplatform_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - techplatform_net
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.7.0
    container_name: techplatform_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - techplatform_net
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  techplatform_net:
    driver: bridge